[POT-12], [POT-13] - User update and soft-delete functions
anton-kolyaev/insurance-2023-july pull request #11
Opened 2023-07-04 10:29 UTC by NorthDragonDuck

Title: Add User Update & Delete Functionality, alter new column with user status at USERS database table

Description: Implements the update of the user and soft deletion of a user by ID. Additionally, it sets up the new column at user table to manage user deletion status, improve previously implemented methods.

Changes Made:
* Created user rest API update functionality to allow change users information at database
* Implemented rest API soft-delete functionality by updating user deletion status
* Added the path of user rest controller put and delete methods to the controller at the security config file and implemented the service methods to interact with it.
* Improve previously implemented methods
* Created unit and integration tests to verify the functionality and correctness of the implemented functions

2023-07-04 11:28 UTC, Dovias approved these changes

2023-07-04 11:28 UTC, Dovias commented on template/src/main/resources/db/changelog/changelog-master.json
Current specification in the liquibase structuring states we should follow version based changelog approach to deal with database stuff, but we could also persist with our current structure as well. Its a matter of preference in this case, but make sure to message me if we would like to leave the structure as it is, since I need to update the specification in that case.

2023-07-04 11:28 UTC, Dovias commented on template/src/main/resources/db/changelog/changes/user_table.sql
Current specification in the liquibase structuring states we should follow version based changelog approach to deal with database stuff, but we could also persist with our current structure as well. Its a matter of preference in this case, but make sure to message me if we would like to leave the structure as it is, since I need to update the specification in that case.

2023-07-05 12:48 UTC, anton-kolyaev requested changes

2023-07-07 11:22 UTC, BlenderEngineer approved these changes

2023-07-10 07:43 UTC, merged