[POT-15] - Implement an API endpoint that assigns functions to a company
anton-kolyaev/insurance-2023-july pull request #14
Opened 2023-07-13 08:30 UTC by NorthDragonDuck

* Implement new function for assigning functions to a company if company is valid
* Add deletion status to company
* Add new method findByIdAndDeletionStatusFalse() to company JPA repository
* Create company_functions table in the database
* Convert JUnit user unit tests to Spock

2023-07-13 17:41 UTC, anton-kolyaev requested changes

2023-07-13 17:41 UTC, anton-kolyaev commented on template/src/main/java/pot/insurance/manager/dto/CompanyDTO.java
> +    @Value("${deletionStatusDefaultValue:false}")
Value? Is it supposed to be set via config?

2023-07-13 17:41 UTC, anton-kolyaev commented on template/src/main/java/pot/insurance/manager/dto/CompanyFunctionsDTO.java
> +    @Value("${companyManagerDefaultValue:false}")
Probably I'm not getting the idea of that. But why you are setting it via config? How it supposed to work?

2023-07-13 17:41 UTC, anton-kolyaev commented on template/src/main/java/pot/insurance/manager/controller/FunctionsRestController.java
> +public class FunctionsRestController {
Can we follow the same naming convention all over around like CompanyFunctionsController/CompanyFunctionsService/CompanyFunctionsRepo ?

2023-07-13 17:41 UTC, anton-kolyaev commented on template/src/main/resources/db/changelog/changes/changelog-release-1.0.sql
> +ALTER TABLE IF EXISTS `companies`
create new file for new changeset please

2023-07-13 17:41 UTC, anton-kolyaev commented on template/src/test/java/pot/insurance/manager/FunctionsIntegrationTests.java
> +    private FunctionsService functionsService;
Use `@Spy` on this Bean and `@MockBean` on beans for repositories so it will check whole (almost) chain of call.

2023-07-13 17:41 UTC, anton-kolyaev commented on template/src/test/java/pot/insurance/manager/FunctionsIntegrationTests.java
> +public class FunctionsIntegrationTests {
Spock?

2023-07-14 09:17 UTC, NorthDragonDuck commented on template/src/main/java/pot/insurance/manager/dto/CompanyDTO.java
> +    @Value("${deletionStatusDefaultValue:false}")
Yes, it should be via config https://www.baeldung.com/spring-value-defaults

2023-07-14 09:17 UTC, NorthDragonDuck commented on template/src/main/java/pot/insurance/manager/dto/CompanyFunctionsDTO.java
> +    @Value("${companyManagerDefaultValue:false}")
The idea of using '@Values', to not set defaults value in SQL code because it is difficult to make properly assigned defaults when JPA repository almost always send not defined values as null and at SQL we have specification for a lot of fields NOT NULL what make data conflict sometimes

2023-07-14 09:18 UTC, NorthDragonDuck commented on template/src/main/java/pot/insurance/manager/controller/FunctionsRestController.java
> +public class FunctionsRestController {
I thought a could use the same controller/service/mapper in future for user functions assignment because constructor and data setted almost similar

2023-07-14 15:22 UTC, anton-kolyaev requested changes

2023-07-14 15:22 UTC, anton-kolyaev commented on template/src/test/groovy/controller/CompanyFunctionsRestControllerSpec.groovy
> +            def companyFunctionsDTO = new CompanyFunctionsDTO(
that's why you should use Builder

2023-07-14 15:22 UTC, anton-kolyaev commented on template/src/test/groovy/controller/UserRestControllerSpec.groovy
> +            def userDTO = new UserDTO(
Builder

2023-07-17 05:51 UTC, anton-kolyaev approved these changes

2023-07-17 08:13 UTC, pkondratas approved these changes

2023-07-17 08:14 UTC, merged