[POT-16] - Implement an API endpoint that assigns specific company's functions to a user and assign user to company
anton-kolyaev/insurance-2023-july pull request #16
Opened 2023-07-17 08:33 UTC by NorthDragonDuck

2023-07-17 08:51 UTC, anton-kolyaev requested changes

2023-07-17 08:51 UTC, anton-kolyaev commented on template/src/test/groovy/integration/CompanyIntegrationSpec.groovy
> +        UUID.randomUUID() | "US" | "Example company" | "example.com" | "email@gmail.com" |       false    | 201
add case(s) where user deleted as well

2023-07-17 08:51 UTC, anton-kolyaev commented on template/src/main/java/pot/insurance/manager/service/CompanyService.java
> +            .ifPresent(c -> {throw new DataValidationException(DataValidation.Status.COMPANY_ID_EXISTS);});
👍

2023-07-17 08:51 UTC, anton-kolyaev commented on template/src/main/resources/db/changelog/changelog-master.json
> +                "file": "changes/changelog-release-1.2.sql"
NIT: you can choose naming pattern to make more obvious what changeset is about and probably mention author and date when changeset has been created.

2023-07-17 08:51 UTC, anton-kolyaev commented on template/src/main/java/pot/insurance/manager/service/UserFunctionsServiceImpl.java
> +            System.out.println(userFunctions);
!Use logger instead

2023-07-17 08:51 UTC, anton-kolyaev commented on template/src/main/java/pot/insurance/manager/service/UserFunctionsServiceImpl.java
> +    public UserFunctionsDTO modifyUserFunctionsDTO(UserFunctionsDTO userFunctionsDTO, CompanyFunctions companyFunctions) {
Should it be public?

2023-07-17 13:51 UTC, anton-kolyaev requested changes

2023-07-17 13:51 UTC, anton-kolyaev commented on template/src/main/java/pot/insurance/manager/service/CompanyService.java
> +                .filter(company -> !company.getDeletionStatus())
You need to add smth like 
`companyRepository.findAllWithDeletionStatusFalse()`
instead

2023-07-17 13:51 UTC, anton-kolyaev commented on template/src/test/groovy/integration/UserFunctionsIntegrationSpec.groovy
> +                    .content(new ObjectMapper().writeValueAsString(userFunctionsDTO)))
on line 44 you already have global ObjectMapper - do you need a new over here?

2023-07-17 15:32 UTC, anton-kolyaev approved these changes

2023-07-17 17:00 UTC, pkondratas submitted a review, later dismissed

2023-07-17 17:02 UTC, anton-kolyaev commented
@NorthDragonDuck  resolve conflicts

2023-07-17 18:21 UTC, anton-kolyaev commented on template/src/main/java/pot/insurance/manager/service/UserFunctionsServiceImpl.java
> +        Arrays.stream(userFunctionsDTO.getClass().getDeclaredFields())
why reflection instead of simple
`companyFunctions.setCompanyManager(userFunctionsDTO.isCompanyManager())`
or even use mapper?

2023-07-17 19:41 UTC, NorthDragonDuck commented on template/src/main/java/pot/insurance/manager/service/UserFunctionsServiceImpl.java
> +        Arrays.stream(userFunctionsDTO.getClass().getDeclaredFields())
Thought it will be a good solution to make functions comparison a little bit universal...

2023-07-18 06:48 UTC, anton-kolyaev approved these changes

2023-07-18 09:30 UTC, pkondratas approved these changes

2023-07-18 09:35 UTC, merged