User functions implementation
anton-kolyaev/insurance-2023-july pull request #6
Opened 2023-06-27 08:32 UTC by NorthDragonDuck

Title: Add User Create & Read Functionality and Configure Gradle for Tests

Description: Implements the creation of the user, find by ID, and find all functionality. Additionally, it sets up the necessary Gradle configuration for tests, adds the path to the controller at the security config file, and includes tests for the implemented functions.

Changes Made:
* Created user rest api creation functionality to allow new users to be added to database
* Implemented find by ID functionality to retrieve a specific user by their ID
* Added find all functionality to retrieve all users in the database
* Configured Gradle to include necessary dependencies and settings for running tests
* Added the path of user rest controller post and get methods to the controller at the security config file
* Created unit and integration tests to verify the functionality and correctness of the implemented functions
* Fix previous database setup in .yaml file

2023-06-28 11:24 UTC, anton-kolyaev requested changes

2023-06-28 11:24 UTC, anton-kolyaev commented on template/build.gradle
> +	implementation libs.groovy.all
do we need it as `implementation` or `testImplementation` is enough?

2023-06-28 11:24 UTC, anton-kolyaev commented on template/src/main/java/pot/insurance/manager/controller/UserRestController.java
> +    @PostMapping("/v1/users")
add common "/v1/users" part on the Controller level as:
```
@RequestMapping("/v1/users")
public class UserRestController {
```

2023-06-28 11:24 UTC, anton-kolyaev commented on template/src/main/java/pot/insurance/manager/controller/UserRestController.java
> +    public UserRestController(UserService theUserService) {
Inject (@Autowire) into constructor instead of on the field

2023-06-28 11:24 UTC, anton-kolyaev commented on template/src/main/java/pot/insurance/manager/controller/UserRestController.java
> +        if(userDTO == null){
The Controller should as dumb as possible, move all business logic to Service layer

2023-06-28 11:24 UTC, anton-kolyaev commented on template/src/main/java/pot/insurance/manager/controller/UserRestController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(dbUser);
Return UserDTO type. You need not to wrap it into ResponseEntity when you use RestController. To add custom status use `@ResponseStatus(HttpStatus.CREATED)` on method level

2023-06-28 11:24 UTC, anton-kolyaev commented on template/src/main/java/pot/insurance/manager/controller/UserRestController.java
> +        return ResponseEntity.status(HttpStatus.OK).body(userService.findAll());
HttpStatus.OK is default you need not to add it explicitly

2023-06-28 11:24 UTC, anton-kolyaev commented on template/src/main/java/pot/insurance/manager/controller/UserRestController.java
> +    private UserService userService;
can be final

2023-06-28 11:24 UTC, anton-kolyaev commented on template/src/main/java/pot/insurance/manager/controller/UserRestController.java
> +            return ResponseEntity.status(HttpStatus.NOT_FOUND).body("User not found!");
Throw custom exception from Service layer and catch it on Controller via `@ExceptionHandler`

2023-06-28 11:24 UTC, anton-kolyaev commented on template/src/main/java/pot/insurance/manager/dto/UserDTO.java
> +    private String first_name;
Use camel case for POJO fields (ok for db columns)

2023-06-28 11:24 UTC, anton-kolyaev commented on template/src/main/java/pot/insurance/manager/service/UserServiceImpl.java
> +    @Transactional
Not necessary, but ok

2023-06-28 11:24 UTC, anton-kolyaev commented on template/src/main/java/pot/insurance/manager/service/UserServiceImpl.java
> +            throw new RuntimeException("User not found for id: " + id);
Use your own custom exception

2023-06-28 11:24 UTC, anton-kolyaev commented on template/src/main/java/pot/insurance/manager/service/UserServiceImpl.java
> +        if(userDTO.isPresent()){
I'm quite sure that you can refactor it in something more beautiful.

2023-06-28 11:24 UTC, anton-kolyaev commented on template/src/main/resources/db/changelog/changes/user_table.sql
> -`user_name` VARCHAR(35) NOT NULL,
!!! Never alter merged changelogs. Add your own if you need to.

2023-06-29 04:50 UTC, anton-kolyaev commented on template/src/main/java/pot/insurance/manager/dto/UserDTO.java
> +    private String first_name;
```
@Column(name = "first_name")
private String firstName;
```

2023-06-29 04:58 UTC, anton-kolyaev commented on template/src/main/java/pot/insurance/manager/dto/UserDTO.java
> +public class UserDTO {
Separate Entity from DTO:
DTO - object to transfer via REST API
Entity - object to store in DB
You can use https://mapstruct.org/ to make your life easier

2023-06-29 04:59 UTC, anton-kolyaev commented on template/src/main/java/pot/insurance/manager/service/UserServiceImpl.java
> +            if ((e.getMessage().contains("USERNAME ")) && (e.getMessage().contains("Unique index or primary key violation"))) {
Put this logic to ExceptionHandler

2023-06-30 04:07 UTC, anton-kolyaev requested changes

2023-06-30 04:07 UTC, anton-kolyaev commented on template/src/main/resources/db/changelog/changes/user_table_001.sql
> +-- DROP SCHEMA IF EXISTS `java_internship`;
Imagine that there is already existing application with thousands of users who have signed in. Your script drops all of them and in the most cases our business lost all clients became bankrupt and all team fired. 
NO breaking changes on data please.

2023-06-30 07:30 UTC, anton-kolyaev requested changes

2023-06-30 07:30 UTC, anton-kolyaev commented on template/src/main/java/pot/insurance/manager/service/UserServiceImpl.java
> +    private UserRepository userRepository;
could be final

2023-06-30 07:30 UTC, anton-kolyaev commented on template/src/main/java/pot/insurance/manager/exception/rest/UserRestExceptionHandler.java
> +    if (exc.getMessage().contains("USERNAME") && exc.getMessage().contains("Unique index or primary key violation")) {
To build your business logic on top of part of 3rd party message is a quite bad practice. 
Let leave it for now to merge current PR but please create TechDebt task in Jira to fix that.

2023-06-30 07:33 UTC, anton-kolyaev commented on template/src/main/java/pot/insurance/manager/controller/UserRestController.java
> +    public Object findUserById(@PathVariable UUID user_id){
user_id -> userId

2023-06-30 10:00 UTC, anton-kolyaev submitted a review, later dismissed
Rename your PR and commits message to smth like:
`[POT-1] Save and  get users`
And remember to squash your commits before merge

2023-06-30 10:50 UTC, Dovias requested changes
In my opinion, it needs some changes with liquibase changelogs.

2023-06-30 10:50 UTC, Dovias commented on template/src/main/resources/db/changelog/changelog-master.json
> +  "databaseChangeLog": [
You could do this version suffixing, but in my opinion, this would get out of hand with lots of changes in a database schema. Who wants to search hundreds of files, when you can just search one with a text editor, right?

2023-06-30 10:50 UTC, Dovias commented on template/src/main/resources/db/changelog/changes/user_table.sql
>  PRIMARY KEY (`id`),
There's no liquibase SQL formatting at all, using changelogs like this defeats the purpose of the whole liquibase versioning concept. 
https://www.liquibase.com/blog/plain-sql
https://docs.liquibase.com/concepts/changelogs/sql-format.html

2023-06-30 10:50 UTC, Dovias commented on template/src/main/resources/db/changelog/changes/user_table_001.sql
> +
There's no liquibase SQL formatting at all, using changelogs like this defeats the purpose of the whole liquibase versioning concept. 
https://www.liquibase.com/blog/plain-sql
https://docs.liquibase.com/concepts/changelogs/sql-format.html

2023-06-30 11:41 UTC, Dovias approved these changes

2023-07-04 05:28 UTC, anton-kolyaev approved these changes

2023-07-04 09:22 UTC, merged